# default values

all:
  cas_server:
    host: cas.univ-avignon.fr
    port: 443
    path:

  ldap_server:
    host: ldap.univ-avignon.fr
    port: 389
    basedn: dc=univ-avignon,dc=fr
    options: {<?php echo LDAP_OPT_PROTOCOL_VERSION ?>: 3}

  bdd_infos:
    user_pass_encrypt: none
    user_table_name: user
    user_login_field: login
    user_pass_field: pass
    user_name_field: name
    user_surname_field: surname
    user_mail_field: mail

  profile_var_translation:
    uid: uid
    name: sn
    surname: givenname
    mail: mail

  url: rdvz.univ-avignon.fr
#  profile_builder_class: uapvProfileBuilderDatabase
  profile_builder_class: uapvProfileBuilderLdap
  authentication_type: ldap
#  authentication_type: bdd 
  user_id: rdvz_user_id
#  user_id: id

  hash_nb_chars: 3

  org_name: "Universit√© d'Avignon et des Pays de Vaucluse"
  mail_sender: "rdvz-admin@univ-avignon.fr"
#  org_name: "Mon RdvZ"
  
  .array:
    languages: 
      fr: fr_FR
      en: en_US
