prod:
  .settings:
    no_script_name:         true
    logging_enabled:        false

dev:
  .settings:
    error_reporting:        <?php echo (E_ALL | E_STRICT)."\n" ?>
    web_debug:              true
    cache:                  false
    no_script_name:         false
    etag:                   false

    enabled_modules: [uapvAuthProfile]

test:
  .settings:
    error_reporting:        <?php echo ((E_ALL | E_STRICT) ^ E_NOTICE)."\n" ?>
    cache:                  false
    web_debug:              false
    no_script_name:         false
    etag:                   false

all:
  .settings:
    i18n:                   true
    default_culture:        fr_FR
    # Form security secret (CSRF protection)
    csrf_secret:       dfac37facb8499c931c70a84c303594a8f9b55e0     # Unique secret to enable CSRF protection or false to disable
    enabled_modules: [default, authentication, error, autocomplete]
    standard_helpers: [Partial, Cache, Form, I18N]

    # Output escaping settings
    escaping_strategy:      true            # Determines how variables are made available to templates. Accepted values: true, false.
    escaping_method:        ESC_SPECIALCHARS # Function or helper used for escaping. Accepted values: ESC_RAW, ESC_ENTITIES, ESC_JS, ESC_JS_NO_ENTITIES, and ESC_SPECIALCHARS.

    # Cache settings
    lazy_cache_key:         true        # Delays creation of a cache key until after checking whether an action or partial is cacheable

  .actions:                         
    secure_module: auth
    secure_action: wrongcred
    error_404_module: error
    error_404_action: error404

                                    # Uniquement pour login par
    login_module: authentication    # base de donn√©es ou ldap seul.
    login_action: login             # 
